In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat, savemat
import pandas as pd
import scipy.special as SS
import scipy.stats as SSA
import copy
import random
import math
import matplotlib.dates as mdates

In [2]:
data_path = '../data/github/'
import sys
sys.path.append('../codes/')
from data_input import *
from full_contact_matrix import *

### Contact matrix
The rows, similarly, represent the race/ethnicity groups. However, when looking at a row, you're focusing on that specific race/ethnicity group and seeing how many effective contacts it has with each of the groups listed in the columns.

In [18]:
CM_06_community = pd.read_csv(data_path+
                            '/contact_matrix/6_california/contact_matrix/community_ca.csv',
                            index_col='Unnamed: 0')
CM_06_household = pd.read_csv(data_path+
                            '/contact_matrix/6_california/contact_matrix/household_ca.csv',
                            index_col='Unnamed: 0')
CM_06_school = pd.read_csv(data_path+
                            '/contact_matrix/6_california/contact_matrix/school_ca.csv',
                            index_col='Unnamed: 0')  
CM_06_work = pd.read_csv(data_path+
                            '/contact_matrix/6_california/contact_matrix/workplace_prepandemic_ca.csv',
                            index_col='Unnamed: 0')

In [19]:
CM_37_community = pd.read_csv(data_path+
                            '/contact_matrix/37_north_carolina/contact_matrix/community_nc.csv',
                            index_col='Unnamed: 0')
CM_37_household = pd.read_csv(data_path+
                            '/contact_matrix/37_north_carolina/contact_matrix/household_nc.csv',
                            index_col='Unnamed: 0')
CM_37_school = pd.read_csv(data_path+
                            '/contact_matrix/37_north_carolina/contact_matrix/school_nc.csv',
                            index_col='Unnamed: 0')  
### nc folder does not have workplace matrix therefore using california's workplace matrix
CM_37_work = CM_06_work.drop('latino', axis=1)
# CM_37_work = pd.read_csv(data_path+
#                             '/contact_matrix/37_north_carolina/contact_matrix/workplace_prepandemic_ca.csv',
#                             index_col='Unnamed: 0')

In [20]:
populations = pd.read_csv(data_path+'population_data/population_data.csv')
populations_06 = populations[populations['location'] == 6]
populations_37 = populations[populations['location'] == 37]

In [45]:
populations_06['percent'] = populations_06['pop_size'] / populations_06['population']
populations_37['percent'] = populations_37['pop_size'] / populations_37['population']

/var/folders/_0/2l3z2qss74scb88wvbv1szxr0000gn/T/ipykernel_47594/3952200547.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  populations_06['percent'] = populations_06['pop_size'] / populations_06['population']
/var/folders/_0/2l3z2qss74scb88wvbv1szxr0000gn/T/ipykernel_47594/3952200547.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  populations_37['percent'] = populations_37['pop_size'] / populations_37['population']


In [43]:
CM_06_norm_df, CM_06_normalised = get_CM_normalised(race_list_06, populations_06, CM_06_community, CM_06_household, CM_06_school, CM_06_work)
# np.savetxt('CM_06_normalised.csv',CM_06_normalised,delimiter=',')

In [46]:
CM_37_norm_df, CM_37_normalised = get_CM_normalised(race_list_37, populations_37, CM_37_community, CM_37_household, CM_37_school, CM_37_work)
# np.savetxt('CM_37_normalised.csv',CM_37_normalised,delimiter=',')

In [47]:
CM_37_normalised

array([[0.48615909, 0.16468237, 0.17708845, 0.17207009],
       [0.22789413, 0.33120005, 0.21469088, 0.22621495],
       [0.17465027, 0.14183826, 0.49389904, 0.18961242],
       [0.15004304, 0.13886757, 0.16293583, 0.54815357]])

In [48]:
### the above are not correct

Contact matrices should be interpeted as the column representing the 
race/ethnicity of the individual and the row representing the 
race/ethnicity of the contact. Each column sums to the average daily
 number of contacts for 
an individual of a given racial/ethnic group. 

In [30]:
CM_06 = pd.read_csv(data_path+
                            '/contact_matrix/6_california/contact_matrix/full_matrix_pandemic_ca.csv',header=0,index_col=0)

In [8]:
race_list_06

['asian', 'white', 'black', 'latino', 'other']

In [4]:
CM_06_arrary = CM_06.to_numpy().T
CM_06_normalised = CM_06_arrary/(np.sum(CM_06_arrary, axis = 1)[:,None])

In [5]:
# np.savetxt('CM_06_normalised.csv',CM_06_normalised,delimiter=',')

In [6]:
CM_06_normalised

array([[0.50131926, 0.20976253, 0.03430079, 0.22559367, 0.02902375],
       [0.08918129, 0.61549708, 0.03216374, 0.22953216, 0.03362573],
       [0.09169765, 0.20198265, 0.37174721, 0.3023544 , 0.03221809],
       [0.07609861, 0.18220793, 0.03858521, 0.67738478, 0.02572347],
       [0.0994012 , 0.25389222, 0.04191617, 0.25628743, 0.34850299]])

In [9]:
CM_37 = pd.read_csv(data_path+
                            '/contact_matrix/37_north_carolina/contact_matrix/full_matrix_pandemic_nc.csv',header=0,index_col=0)

In [10]:
CM_37_arrary = CM_37.to_numpy().T
CM_37_normalised = CM_37_arrary/(np.sum(CM_37_arrary, axis = 1)[:,None])

In [11]:
np.savetxt('CM_37_normalised.csv',CM_37_normalised,delimiter=',')

In [25]:
CM_37_normalised

array([[0.39370079, 0.40419948, 0.14173228, 0.06036745],
       [0.01833568, 0.78843441, 0.13399154, 0.05923836],
       [0.02050663, 0.39445115, 0.51507841, 0.06996381],
       [0.01789709, 0.38255034, 0.16219239, 0.43736018]])